FROM ubuntu

RUN echo "deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main 9.5" > /etc/apt/sources.list.d/postgres.list
RUN apt-get install -y wget git
RUN wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
RUN apt-get update
RUN apt-get install -y postgresql-9.4 postgresql-server-dev-9.4 libcurl4-openssl-dev build-essential
RUN echo "host all all 0.0.0.0/0 trust" >> /etc/postgresql/9.4/main/pg_hba.conf

RUN git clone https://github.com/edenhill/librdkafka.git /librdkafka
WORKDIR /librdkafka
RUN ./configure && make && make install

COPY . /project

WORKDIR /project
RUN make && make test
